# Generated by Django 5.0.6 on 2026-04-02 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskaisuggestion_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_user_id_0440f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_user_id_b7b7b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_assigne_c4dd42_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_due_dat_d0a0d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskaisuggestion',
            name='suggestion_pending_idx',
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='core_conver_user_id_3e2a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status', '-created_at'], name='core_docume_user_id_dab553_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'file_type'], name='core_docume_user_id_9e6517_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', '-created_at'], name='core_task_user_id_c86f96_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority', '-created_at'], name='core_task_user_id_22edc1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status', '-created_at'], name='core_task_assigne_86bc38_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='core_task_due_dat_3cc367_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='core_task_status_266946_idx'),
        ),
    ]
