# Generated by Django 5.0.6 on 2026-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_notification"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["keywords"], name="core_docume_keyword_7c593e_idx"
            ),
        ),
    ]
