# Generated by Django 5.0.6 on 2026-04-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="core_conv_user_del_upd_idx",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="core_doc_user_stat_del_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="core_msg_conv_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="core_notif_user_read_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="core_task_user_stat_prio_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="core_task_assign_stat_idx",
        ),
        migrations.RemoveIndex(
            model_name="usermemory",
            name="core_mem_user_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="core_emailv_created_96d4e2_idx",
            old_name="core_emailver_created_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresetcode",
            new_name="core_passwo_created_015adc_idx",
            old_name="core_passwordr_created_idx",
        ),
    ]
