# Generated by Django 5.0.6 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_conversation_core_conv_user_del_upd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Vector embedding for semantic search [768-dim or 1536-dim]",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding_model",
            field=models.CharField(
                max_length=50,
                blank=True,
                default="",
                help_text="Model used to generate embedding (e.g., 'text-embedding-3-small')",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding_generated_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["embedding_model"], name="core_docume_embed_model_idx"),
        ),
    ]
