# Generated by Django 5.0.6 on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_documentchunk_embedding_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("login", "User Login"), ("logout", "User Logout"), ("login_failed", "Login Failed"), ("token_refresh", "Token Refresh"), ("password_change", "Password Change"), ("password_reset", "Password Reset"), ("mfa_enabled", "MFA Enabled"), ("mfa_disabled", "MFA Disabled"), ("session_revoked", "Session Revoked"), ("session_revoked_all", "All Sessions Revoked"), ("document_upload", "Document Upload"), ("document_download", "Document Download"), ("document_delete", "Document Delete"), ("document_view", "Document View"), ("task_create", "Task Create"), ("task_update", "Task Update"), ("task_delete", "Task Delete"), ("task_complete", "Task Complete"), ("task_reopen", "Task Reopen"), ("ai_prompt", "AI Prompt"), ("ai_response", "AI Response"), ("ai_suggestion_accepted", "AI Suggestion Accepted"), ("ai_suggestion_rejected", "AI Suggestion Rejected"), ("permission_grant", "Permission Grant"), ("permission_revoke", "Permission Revoke"), ("role_change", "Role Change"), ("export", "Data Export"), ("bulk_delete", "Bulk Delete"), ("settings_change", "Settings Change")], max_length=30)),
                ("severity", models.CharField(choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")], default="info", max_length=10)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceContext",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.CharField(db_index=True, help_text="Unique workspace identifier", max_length=100)),
                ("workspace_name", models.CharField(blank=True, max_length=200)),
                ("business_context", models.JSONField(blank=True, default=dict, help_text="Business-specific context: company info, industry, tone, etc.")),
                ("ai_memory", models.JSONField(blank=True, default=list, help_text="Persistent AI memory: facts, preferences, learned context")),
                ("conversation_summaries", models.JSONField(blank=True, default=list, help_text="Summaries of past conversations for context")),
                ("preferences", models.JSONField(blank=True, default=dict, help_text="Workspace-specific preferences (tone, response style, etc.)")),
                ("is_active", models.BooleanField(default=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_contexts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-last_accessed"],
                "unique_together": {("user", "workspace_id")},
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "-created_at"], name="audit_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event_type", "-created_at"], name="audit_event_created_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["severity", "-created_at"], name="audit_severity_created_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacecontext",
            index=models.Index(fields=["user", "workspace_id"], name="workspace_ctx_user_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacecontext",
            index=models.Index(fields=["workspace_id"], name="workspace_ctx_id_idx"),
        ),
    ]
