# Generated by Django 5.0.6 on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auditlog_workspacecontext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to=core.models.document_file_path)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("change_summary", models.TextField(blank=True, default="")),
                ("change_type", models.CharField(choices=[("created", "Created"), ("edited", "Edited"), ("replaced", "Replaced"), ("minor", "Minor Update")], default="replaced", max_length=20)),
                ("previous_text", models.TextField(blank=True, default="")),
                ("text_diff", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_versions", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="core.document")),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["document", "version_number"], name="core_docver_doc_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["file_hash"], name="core_docver_filehash_idx"),
        ),
    ]
