# Generated by Django 5.0.6 on 2026-05-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_documentversion_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="parent_comment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="replies", to="core.taskcomment"),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["task", "created_at"], name="core_taskcomment_task_created_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["user"], name="core_taskcomment_user_idx"),
        ),
    ]
