# Generated by Django 5.0.6 on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_taskcomment_mentions_threading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="id",
        ),
        migrations.AddField(
            model_name="notification",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(choices=[("task_assigned", "Task Assigned"), ("task_mentioned", "Task Mention"), ("due_date_approaching", "Due Date Approaching"), ("due_date_overdue", "Task Overdue"), ("task_completed", "Task Completed"), ("comment_reply", "Comment Reply"), ("document_shared", "Document Shared"), ("system", "System Notification")], default="system", max_length=30),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.task"),
        ),
        migrations.AddField(
            model_name="notification",
            name="document",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.document"),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.taskcomment"),
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="triggered_notifications", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="websocket_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="websocket_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="push_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "notification_type"], name="core_notif_user_type_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="core_notif_created_idx"),
        ),
        migrations.CreateModel(
            name="TaskSubtask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("todo", "To Do"), ("in_progress", "In Progress"), ("done", "Done")], default="todo", max_length=20)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_subtasks", to=settings.AUTH_USER_MODEL)),
                ("parent_task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="child_subtasks", to="core.task")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_manual", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_entries", to="core.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["task", "start_time"], name="core_timeentry_task_start_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["user", "start_time"], name="core_timeentry_user_start_idx"),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_assigned_in_app", models.BooleanField(default=True)),
                ("task_mentioned_in_app", models.BooleanField(default=True)),
                ("due_date_approaching_in_app", models.BooleanField(default=True)),
                ("due_date_overdue_in_app", models.BooleanField(default=True)),
                ("comment_reply_in_app", models.BooleanField(default=True)),
                ("task_assigned_email", models.BooleanField(default=True)),
                ("task_mentioned_email", models.BooleanField(default=True)),
                ("due_date_approaching_email", models.BooleanField(default=True)),
                ("due_date_overdue_email", models.BooleanField(default=True)),
                ("due_date_warning_hours", models.PositiveIntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_public", models.BooleanField(default=False)),
                ("allow_invite_links", models.BooleanField(default=True)),
                ("default_member_role", models.CharField(choices=[("viewer", "Viewer"), ("member", "Member")], default="member", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_workspaces", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member"), ("viewer", "Viewer")], default="member", max_length=20)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invited_members", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_memberships", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="core.workspace")),
            ],
            options={
                "ordering": ["-role", "joined_at"],
                "unique_together": {("workspace", "user")},
            },
        ),
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.UUIDField()),
                ("permission", models.CharField(choices=[("view", "View"), ("edit", "Edit"), ("delete", "Delete"), ("share", "Share")], max_length=20)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("granted_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="granted_permissions", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="resource_permissions", to=settings.AUTH_USER_MODEL)),
                ("workspace_member", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="resource_permissions", to="core.workspacemember")),
            ],
            options={
                "unique_together": {("resource_type", "resource_id", "user", "permission")},
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="e.g., 'Zapier Production'", max_length=255)),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("scopes", models.JSONField(default=list, help_text="['tasks:read', 'tasks:write', 'documents:read']")),
                ("rate_limit", models.PositiveIntegerField(default=1000, help_text="Requests per hour")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_tokens", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("events", models.JSONField(default=list, help_text="List of event types to subscribe to")),
                ("secret", models.CharField(help_text="Secret for HMAC signature", max_length=255)),
                ("headers", models.JSONField(blank=True, default=dict, help_text="Custom headers")),
                ("is_active", models.BooleanField(default=True)),
                ("retry_count", models.PositiveIntegerField(default=3)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("last_delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhooks", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="webhooks", to="core.workspace")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed"), ("pending", "Pending"), ("retrying", "Retrying")], default="pending", max_length=20)),
                ("webhook", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="core.webhook")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["webhook", "-started_at"], name="core_webhookdelivery_webhook_started_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type", "-started_at"], name="core_webhookdelivery_event_started_idx"),
        ),
        migrations.CreateModel(
            name="ConversationMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("extracted_facts", models.JSONField(blank=True, default=list)),
                ("user_intents", models.JSONField(blank=True, default=list)),
                ("running_summary", models.TextField(blank=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="memory", to="core.conversation")),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
