# Generated by Django 5.2.14 on 2026-05-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_core_models_expansion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="core_docume_embeddi_ba8e26_idx",
            old_name="core_docume_embed_model_idx",
        ),
        migrations.RenameIndex(
            model_name="documentversion",
            new_name="core_docume_documen_bd639e_idx",
            old_name="core_docver_doc_ver_idx",
        ),
        migrations.RenameIndex(
            model_name="documentversion",
            new_name="core_docume_file_ha_c72e0f_idx",
            old_name="core_docver_filehash_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_user_id_f286cd_idx",
            old_name="notification_unread_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_user_id_aa1102_idx",
            old_name="core_notif_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_created_d0c445_idx",
            old_name="core_notif_created_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="core_taskco_task_id_b10483_idx",
            old_name="core_taskcomment_task_created_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="core_taskco_user_id_cc3c51_idx",
            old_name="core_taskcomment_user_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="core_timeen_task_id_220341_idx",
            old_name="core_timeentry_task_start_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="core_timeen_user_id_21d805_idx",
            old_name="core_timeentry_user_start_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="core_webhoo_webhook_e8fe78_idx",
            old_name="core_webhookdelivery_webhook_started_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="core_webhoo_event_t_af1dc3_idx",
            old_name="core_webhookdelivery_event_started_idx",
        ),
        migrations.AddField(
            model_name="task",
            name="ai_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="auto_extracted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extracted_tasks",
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("deep_work", "Deep Work"),
                    ("creative", "Creative"),
                    ("admin", "Administrative"),
                    ("quick", "Quick Task"),
                ],
                default="quick",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
