# Generated by Django 5.2.14 on 2026-05-10 03:44

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0018_rename_core_docume_embed_model_idx_core_docume_embeddi_ba8e26_idx_and_more",
        ),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="document",
            name="visual_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="embedding",
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                help_text="Vector embedding for semantic search [768-dim]",
                null=True,
            ),
        ),
    ]
