# Generated by Django 5.2.14 on 2026-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_document_visual_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
