# Generated by Django 5.2.14 on 2026-09-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_conversation_archived_document_updated_at"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS document_chunk_embedding_hnsw_idx
                ON core_documentchunk
                USING hnsw (embedding vector_cosine_ops)
                WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS document_chunk_embedding_hnsw_idx;
            """,
        ),
    ]