# Generated by Django 6.0.2 on 2026-09-25 06:14

import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_documentchunk_embedding_hnsw_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usermemory",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                help_text="Vector embedding for semantic search [768-dim]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usermemory",
            name="embedding_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermemory",
            name="embedding_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model used to generate embedding (e.g., 'gemini-embedding-001')",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["embedding_model"], name="core_userme_embeddi_961ba6_idx"
            ),
        ),
    ]
