# Generated by Django 6.0.2 on 2026-09-25 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_usermemory_embedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborating_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
