# Generated by Django 6.0.2 on 2026-09-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_workspace_invitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmemory",
            name="conversation",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="core_goal_busines_9159ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="core_goal_busines_42b412_idx",
        ),
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="metric",
            name="core_metric_busines_cace66_idx",
        ),
        migrations.DeleteModel(
            name="ConversationMemory",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="business_profile",
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
    ]
