# Generated by Django 6.0.2 on 2026-09-30 08:58

from django.db import migrations, models


def flag_personal_workspaces(apps, schema_editor):
    """Mark the Personal workspaces created by migration 0027 as is_personal."""
    Workspace = apps.get_model('core', 'Workspace')
    Workspace.objects.filter(name="Personal", is_personal=False).update(is_personal=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_cleanup_workspacecontext_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="is_personal",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for a user's auto-created private Personal workspace",
            ),
        ),
        migrations.RunPython(flag_personal_workspaces, migrations.RunPython.noop),
    ]
